import {
  ada,
  bch,
  bnb,
  btc,
  doge,
  eth,
  shib,
  solana,
  usdc,
  usdttether,
  xrp,
} from "./past";

export const cryptoMenus = ["MostPopular", "BiggestMovers", "Recommendations"];

export const coins = [
  {
    id: "btc-bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    rank: 1,
    is_new: false,
    is_active: true,
    type: "coin",
    logo: "https://static.coinpaprika.com/coin/btc-bitcoin/logo.png",
    history: btc,
    current_price: 75355.67,
    last_price: 74305.67,
  },
  {
    id: "eth-ethereum",
    name: "Ethereum",
    symbol: "ETH",
    rank: 2,
    is_new: false,
    is_active: true,
    type: "coin",
    logo: "https://static.coinpaprika.com/coin/eth-ethereum/logo.png",
    history: eth,
    current_price: 3956.42,
    last_price: 3855.94,
  },
  {
    id: "usdt-tether",
    name: "Tether",
    symbol: "USDT",
    rank: 3,
    is_new: false,
    is_active: true,
    type: "token",
    logo: "https://static.coinpaprika.com/coin/usdt-tether/logo.png",
    history: usdttether,
    current_price: 1.500831,
    last_price: 1.000414,
  },
  {
    id: "bnb-binance-coin",
    name: "Binance Coin",
    symbol: "BNB",
    rank: 4,
    is_new: false,
    is_active: true,
    type: "coin",
    logo: "https://static.coinpaprika.com/coin/bnb-binance-coin/logo.png",
    history: bnb,
    current_price: 605.02,
    last_price: 584.52,
  },
  {
    id: "sol-solana",
    name: "Solana",
    symbol: "SOL",
    rank: 5,
    is_new: false,
    is_active: true,
    type: "coin",
    logo: "https://static.coinpaprika.com/coin/sol-solana/logo.png",
    history: solana,
    current_price: 187.07,
    last_price: 186.07,
  },
  {
    id: "xrp-xrp",
    name: "XRP",
    symbol: "XRP",
    rank: 6,
    is_new: false,
    is_active: true,
    type: "coin",
    logo: "https://static.coinpaprika.com/coin/xrp-xrp/logo.png",
    history: xrp,
    current_price: 1.62323,
    last_price: 0.621214,
  },
  {
    id: "usdc-usd-coin",
    name: "USDC",
    symbol: "USDC",
    rank: 8,
    is_new: false,
    is_active: true,
    type: "token",
    logo: "https://static.coinpaprika.com/coin/usdc-usdc/logo.png",
    history: usdc,
    current_price: 2.500802,
    last_price: 1.000761,
  },
  {
    id: "doge-dogecoin",
    name: "Dogecoin",
    symbol: "DOGE",
    rank: 9,
    is_new: false,
    is_active: true,
    type: "coin",
    logo: "https://static.coinpaprika.com/coin/doge-dogecoin/logo.png",
    history: doge,
    current_price: 0.215931,
    last_price: 0.410032,
  },
  {
    id: "ada-cardano",
    name: "Cardano",
    symbol: "ADA",
    rank: 10,
    is_new: false,
    is_active: true,
    type: "coin",
    logo: "https://static.coinpaprika.com/coin/ada-cardano/logo.png",
    history: ada,
    current_price: 1.649604,
    last_price: 0.649385,
  },
  {
    id: "shib-shiba-inu",
    name: "Shiba Inu",
    symbol: "SHIB",
    rank: 12,
    is_new: false,
    is_active: true,
    type: "token",
    logo: "https://static.coinpaprika.com/coin/shib-shiba-inu/logo.png",
    history: shib,
    current_price: 0.00003102,
    last_price: 0.00003137,
  },
  {
    id: "bch-bitcoin-cash",
    name: "Bitcoin Cash",
    symbol: "BCH",
    rank: 15,
    is_new: false,
    is_active: true,
    type: "coin",
    logo: "https://static.coinpaprika.com/coin/bch-bitcoin-cash/logo.png",
    history: bch,
    current_price: 592.21,
    last_price: 559.6,
  },
];

const copyCoins = [...coins];
export const trimCoins = copyCoins.splice(-6);
export const newTrimCoins = [...copyCoins].reverse();
